@isTest
private class AttachmentController_Test {

     static testMethod void myUnitTest() {
         AttachmentController.uploadAttachment('V0lORE9XUw0KPT09PT09PQ0KdXNlcjogb3JhY2xlIHB3ZDogQ2NhbmFseXplcjENCnVzZXI6IEFkbWluaXN0cmF0b3IgcHdkOiBNaW5vc3NlXzANCg0KT1JBQ0xFDQo9PT09PT0NCg0KREFUQUJBU0UgTkFNRTogT1JBMTJDIC0gcGx1Z2dhYmxlIG5hbWU6IHBkYk9SQTEyQw0KYWRtaW4gcGFzc3dvcmQ6IENjYW5hbHl6ZXIxDQoNCnN5c3RlbS9tYW5hZ2VyDQpzeXMvbWFuYWdlcg0KDQoNClNjaGVtaToNCg0KZ2VuX2NtZS9nZW5lc3lzDQpnZW5faXhuL2dlbmVzeXMNCmdlbl91Y3MvZ2VuZXN5cw0KZ2VuX29jcy9nZW5lc3lzDQoNCg0K', 'text/plain', 'text.txt','02s3i000005Cbx0AAC');  
        AttachmentController.traceAction('1', '2', 'myfile.txt','ixnmgr down');
        }
}